version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mibici_api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - POSTGRES_HOST=postgres
    depends_on:
      - mlflow
    restart: always

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    container_name: mibici_mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql://mlflow:mlflow@postgres/mlflow_db
      - MLFLOW_ARTIFACT_URI=s3://mlflow/
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    command: >
      /bin/sh -c "pip install psycopg2 && 
                  mlflow server --backend-store-uri postgresql://mlflow:mlflow@postgres/mlflow_db --artifacts-destination s3://mlflow/ --host 0.0.0.0 --port 5000"
    depends_on:
      - postgres
      - minio
    restart: always

  postgres:
    image: postgres:13
    container_name: mibici_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  minio:
    image: minio/minio:latest
    container_name: mibici_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    restart: always

  retrain:
    build:
      context: .
      dockerfile: retrain.Dockerfile
    container_name: mibici_retrain
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - POSTGRES_HOST=postgres
    restart: always

volumes:
  postgres_data:
  minio_data:
