channels:
- conda-forge
dependencies:
- python=3.10.14
- pip<=24.0
- pip:
  - mlflow==2.20.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.2.2
  - psutil==5.9.0
  - scikit-learn==1.6.0
  - scipy==1.15.0
name: mlflow-env
